// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ClearHistory():Promise<boolean>;

export function DeleteMeasurement(arg1:number):Promise<boolean>;

export function GetHistory(arg1:string):Promise<Array<models.MeasurementDTO>>;

export function RunMeasurement():Promise<models.MeasurementDTO>;
