// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHistory() {
  return window['go']['backend']['VeloApp']['GetHistory']();
}

export function RunMeasurement() {
  return window['go']['backend']['VeloApp']['RunMeasurement']();
}
