// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHistory(arg1) {
  return window['go']['backend']['VeloApp']['GetHistory'](arg1);
}

export function RunMeasurement() {
  return window['go']['backend']['VeloApp']['RunMeasurement']();
}
